### ISSUE TITLE
gradle bootRun won't pass system params

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/boot-microservice#5]
Scenario:

I want to run

```
gradle bootRun -Dspring.profiles.active=prod
```

what I constantly receive is info that no spring profile has been passed.

WORKAROUND:

in build.gradle pass:

```
project.gradle.projectsEvaluated {
    applicationDefaultJvmArgs = ['-Dspring.profiles.active=prod']
}
```

Maybe it makes ANY sense to you but believe it or not but Spring Boot takes System params from

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-gradle-plugin/src/main/groovy/org/springframework/boot/gradle/run/RunPluginFeatures.java

a project property called 'applicationDefaultJvmArgs'. ?!

**Comment by peterbosalliandercom** [comment]
Put this in the build.gradle


bootRun {
	systemProperty "spring.profiles.active", "local"
}

**Comment by peterbosalliandercom** [comment]
then start bootrun
