### ISSUE TITLE
Service is not registered in ZooKeeper

### ISSUE THREAD

**Issue by rtti** [4finance/boot-microservice#85]
I have  microservice.json:

```{
  "rest": {
    "this": "greeting"
  }
}```

and rest controller:

```java
@RestController
@RequestMapping("rest")
public class GreetingController {

    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    @RequestMapping("/greeting")
    public Greeting greeting(@RequestParam(value="name", defaultValue="World") String name) {
        return new Greeting(counter.incrementAndGet(),
                            String.format(template, name));
    }
}
```
and app configuration:

```java
@SpringBootApplication
@EnableServiceDiscovery
@EnableServiceRestClient
@PropertySource("classpath:prop.properties")
public class ApplicationServer {

    public static void main(String[] args) {

        ApplicationContext ctx =  SpringApplication.run(ApplicationServer.class, args);
        ServiceRestClient serviceRestClient = (ServiceRestClient) ctx.getBean("serviceRestClient");

        String response =  serviceRestClient.forService("greeting")
                .get()
                .onUrl("greeting")
                .anObject()
                .ofType(String.class);

        System.out.println(response);

    }
}
```

So when I start the app I get exception:

java.util.NoSuchElementException: greeting is not our dependency, available: []
	at com.ofg.infrastructure.discovery.ZookeeperServiceResolver.resolveAlias(ZookeeperServiceResolver.groovy:46)
.....
It seems like "greeting " is not registered in zooKeeper.

This is a screenshot of my exhibitor:
http://screencast.com/t/glmCCUly

And this is a log:
http://screencast.com/t/v6805dIE

**Comment by mariuszs** [comment]
greeting is not dependency, it is your application alias

**Comment by marcingrzejszczak** [comment]
Oleg maybe before we go any further with this you could watch this presentation:

http://www.slideshare.net/MarcinGrzejszczak/4financeit-microservices-032015-lodz

then you should know more preciesly who is a collaborator, how the microservice.json is configured etc. 

Of course in case of any question do not hesitate to contact us :)

**Comment by mariuszs** [comment]
Correct microservice.json

```{
  "rest": {
    "this": "greeting",
    "dependencies": {
      "greeting": {
        "path": "greeting"
      }
    }
  }
}```

Now you can call `serviceRestClient.forService("greeting")`

**Comment by rtti** [comment]
I changed microservice.json as above but now I get : 
2015-05-05 15:43:21.522 ERROR 14300 --- [           main] .StubDownloader$RemoteDependencyResolver : Unable to resolve dependency in stub repository [http://dl.bintray.com/4finance/micro]. Reason: [connection error -> Error grabbing Grapes -- [unresolved dependency: greeting#-stubs;latest.default: not found]]


java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: greeting#-stubs;latest.default: not found]

despite the fact that I have rigth configuraton in my property file:
stubrunner.use-microservice-definitions=true
stubrunner.stubs.repository.root=http://dl.bintray.com/4finance/micro
stubrunner.stubs.group=com.ofg
stubrunner.stubs.module=stub-runner-examples

And the second exception appears:
com.ofg.infrastructure.web.resttemplate.custom.ResponseException: Status code: [404], Headers: [[Server:[Apache-Coyote/1.1], Content-Type:[application/json;charset=UTF-8], Transfer-Encoding:[chunked], Date:[Tue, 05 May 2015 12:43:22 GMT]]], Body: [{"timestamp":1430829802725,"status":404,"error":"Not Found","message":"No message available","path":"/greeting"}]
.....

I can't see the new service in my exhibitor as well, what does it mean? Maybe should I point to the my zooKeeper by some way ?

I also read the presentation, a lot of things become more clear :)

**Comment by marcingrzejszczak** [comment]
Could you please tell us how are you running your application?

If you are running in either `test` or `dev` mode your collaborators (thus yourself) will be stubbed. Since you have not created that stub (first warning) then you will fail to call any of its endpoints (second warning).

If however you boot up local instance of Zookeeper and run the applciation in `prod` profile then you should be able to shoot a request to yourself (which makes no sense obviously ;) ).

**Comment by rtti** [comment]
Sorry for my ignorance and please correct if I make mistakes:

I have a zooKeeper instance that is launched on localhost:2181
Here is my zoo.cfg:
#Auto-generated by Exhibitor - Tue May 05 15:36:45 EEST 2015
#Tue May 05 15:36:45 EEST 2015
clientPort=2181
dataDir=D\:\\ZooKeeper\\dataDir\\zoo
server.112=localhost\:2888\:3888
syncLimit=5
tickTime=2000
initLimit=10
dataLogDir=D\:\\ZooKeeper\\dataDir\\zoo

Also I have a spring boot app and I just run main method of my Application class.

What else should I pay attention to?

**Comment by mariuszs** [comment]
Btw, second shot in `dev` mode should call real application. 

Run your application with `-DAPP_ENV=prod`

**Comment by rtti** [comment]
Here is src of my project :
https://github.com/rtti/micro-infra-spring-example

**Comment by mariuszs** [comment]
Correct service invocation:

```java
 String response = serviceRestClient.forService("greeting")
                .get()
                .onUrl("rest/greeting")
                .anObject()
                .ofType(String.class);
```

https://github.com/rtti/micro-infra-spring-example/pull/1/files

**Comment by rtti** [comment]
Thanks a lot! This works! :)

And, finally I have two question about micro-infra-spring:

1) I have a new UserController:
@RestController
@RequestMapping("user")
public class UserController {

    @RequestMapping("/get")
    public String getUser() {
        return "Return a user";
    }
}
and corresponding microservice.json:
{
  "rest": {
    "this": "greeting",
    "dependencies": {
      "greeting": {
        "path": "greeting"
      },
      "user": {
        "path": "user/get"
      }
    }
  }
}

Is it right to send get request as :
        String response =  serviceRestClient.forService("user")
                .get()
                .onUrl("user/get")
                .anObject()
                .ofType(String.class);

Or maybe on Url "rest/user/get"?
In any case I get 
com.ofg.infrastructure.discovery.ServiceUnavailableException: Service with name [user/get] is unavailable

2) As I understand micro-infra-spring uses embedded ZooKeeper. How can I connect to the separate instance of my ZooKeeper (e.g. which is launched on localhost:2181)

**Comment by mariuszs** [comment]
1) Correct `microservice.json`:

```{
  "rest": {
    "this": "greeting",
    "dependencies": {
      "greeting": {
        "path": "greeting"
      }
    }
  }
}
```
Call:

```java
String response = serviceRestClient.forService("greeting")
.get()
.onUrl("user/get")
.anObject()
.ofType(String.class);
```

2) In `dev` and `test` profile zookeeper is embedded. In `prod` profile is not. Take look at my test: https://github.com/rtti/micro-infra-spring-example/blob/master/src/test/java/hello/ApplicationServerTest.java - it is using external zookeper configured in test.

**Comment by rtti** [comment]
Right, thank you!
