### ISSUE TITLE
@PackageScope of HealthCheckConfiguration beans

### ISSUE THREAD

**Issue by rtti** [4finance/boot-microservice#87]
I don't sure that it is an issue of library, but I can't use any of beans defined in com.ofg.infrastructure.healthcheck.HealthCheckConfiguration because all of them have @PackageScope annotation.

Maybe there is a workaround how to use these beans?
Or some example?

**Comment by marcingrzejszczak** [comment]
Are you sure you're using some decent version of micro-infra? :P

```groovy
/**
 * Registers {@link PingController} (the microservice health check controller) and {@link CollaboratorsConnectivityController} (provider of a state of microservice connection with dependent services).
 *
 * @see PingController
 * @see CollaboratorsConnectivityController
 */
@CompileStatic
@Configuration
@Import(CollaboratorsConfiguration)
class HealthCheckConfiguration {

    @Bean
    PingController pingController() {
        return new PingController()
    }

    @Bean
    CollaboratorsConnectivityController collaboratorsConnectivityController(CollaboratorsStatusResolver collaboratorsStatusResolver) {
        return new CollaboratorsConnectivityController(collaboratorsStatusResolver)
    }

    @Bean
    MicroserviceConfigurationController microserviceConfigurationController(@Value('${microservice.config.file:classpath:microservice.json}') Resource microserviceConfig) {
        return new MicroserviceConfigurationController(microserviceConfig)
    }

}
```

It's not package scoped....

**Comment by rtti** [comment]
The problem is that I can't use these beans :)
http://screencast.com/t/l9KdT2ehK

**Comment by marcingrzejszczak** [comment]
Why on earth would you want to autowire those fields?!

Just import it and shoot a request to check it out.

**Comment by rtti** [comment]
I am a little confused. What should I import?
@Import(com.ofg.infrastructure.healthcheck.HealthCheckConfiguration.class)
Is it enough?
And how can I "shoot a request to check it out"?
Could you provide some example?

**Comment by marcingrzejszczak** [comment]
Oleg I'm closing this ticket because it's invalid and I answered your question on Gitter.

BTW do you know how exactly Spring works, what is the @Configuration annotation and what is a Spring Controller? Please respond on Gitter.
