### ISSUE TITLE
Gradle 2.5 update

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/boot-microservice#90]
Is there any reason why we stick with Gradle 2.2.1 ?

@szpak ? :P

**Comment by szpak** [comment]
Possibly - [#366](https://github.com/4finance/micro-infra-spring/issues/366). Related spring-boot [issue](https://github.com/spring-projects/spring-boot/issues/2679) is still open, but it would be needed to check it with Gradle 2.4.

**Comment by hanskoff** [comment]
there is already 2.7 ;)

**Comment by kamilszymanski** [comment]
We're already using v. 2.7: https://github.com/4finance/boot-microservice/blob/master/gradle/wrapper/gradle-wrapper.properties
