### ISSUE TITLE
project bootstrap scripts (like yeoman, lazybones or maven archetype)

### ISSUE THREAD

**Issue by szimano** [4finance/boot-microservice#91]
ideally the script should ask you few questions (or have them passed as program arguments) with things like project name, root package, url to properties repo etc. and create a new copy of the app

**Comment by marcingrzejszczak** [comment]
Things that you have to manually change are:
- accurest stubs root folder (group, name, project name) [project structure]
- accurest configuration (base class for tests) [build.gradle]
- root project name [settings.gradle]
- all paths to support new package structure (com.ofg -> com.some.other.company)

**Comment by marcingrzejszczak** [comment]
Initial approach done - you can test it with:

```
./gradlew setup --no-deamon
```
